@echo off
title P99 Damage Meter

:: Resolve paths relative to this batch file (inside the p99-meter folder)
set "METER_DIR=%~dp0"
for %%i in ("%~dp0..") do set "EQ_DIR=%%~fi"

if not exist "%EQ_DIR%\eqgame.exe" (
    echo.
    echo   [ERROR] eqgame.exe not found in parent directory.
    echo.
    echo   This folder must be inside your EverQuest directory.
    echo   Expected structure:
    echo.
    echo     Your EverQuest Folder\
    echo       eqgame.exe
    echo       p99-meter\           ^<-- this folder
    echo         Setup.bat
    echo         p99-meter.exe
    echo.
    pause
    exit /b 1
)

if not exist "%METER_DIR%p99-meter.exe" (
    echo.
    echo   [ERROR] p99-meter.exe not found.
    echo.
    echo   The installation appears incomplete or corrupted.
    echo   Please re-download and extract the zip file.
    echo.
    pause
    exit /b 1
)

:: Kill any stale meter instance
taskkill /F /IM p99-meter.exe >nul 2>&1
timeout /t 1 /nobreak >nul

:: Launch the damage meter.
:: Uses try/catch so Process::Start failures (permissions, SmartScreen) set exit code 1.
:: The path is inside the double-quoted -Command string, safe even with parens in paths.
powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -Command "try { $psi = New-Object System.Diagnostics.ProcessStartInfo; $psi.FileName = '%METER_DIR%p99-meter.exe'; $psi.CreateNoWindow = $true; $psi.UseShellExecute = $false; [void][System.Diagnostics.Process]::Start($psi) } catch { exit 1 }"
if %errorlevel% neq 0 goto :launch_failed

:: Give the process a moment to start, then verify it's running
timeout /t 2 /nobreak >nul
tasklist /FI "IMAGENAME eq p99-meter.exe" 2>nul | find /I "p99-meter.exe" >nul
if errorlevel 1 goto :meter_crashed
goto :meter_ok

:launch_failed
echo.
echo   [ERROR] Windows refused to start p99-meter.exe.
echo.
echo   Common fixes:
echo     1. Run Setup.bat first to unblock downloaded files
echo     2. Right-click p99-meter.exe, Properties, check "Unblock"
echo     3. Add the p99-meter folder to your antivirus exclusions
echo.
pause
exit /b 1

:meter_crashed
echo.
echo   [WARNING] p99-meter.exe started but exited immediately.
echo   It may have crashed on startup.
echo.
if exist "%METER_DIR%p99-meter.log" (
    echo   A log file exists at:
    echo     %METER_DIR%p99-meter.log
    echo   Please send this file for troubleshooting.
    echo.
    pause
    exit /b 1
)
if exist "%APPDATA%\p99-meter\p99-meter.log" (
    echo   A log file exists at:
    echo     %APPDATA%\p99-meter\p99-meter.log
    echo   Please send this file for troubleshooting.
    echo.
    pause
    exit /b 1
)
echo   No log file was created, which means it crashed very early.
echo.
echo   Try double-clicking p99-meter.exe directly to see if
echo   Windows shows an error dialog.
echo.
echo   Common causes:
echo     - Windows SmartScreen or antivirus blocked the app
echo     - Missing Visual C++ runtime (install from microsoft.com)
echo     - Run Setup.bat first to unblock downloaded files
echo.
pause
exit /b 1

:meter_ok
:: CPU affinity mask — generated by Setup.bat, falls back to 0xFF (first 8 logical processors).
:: On Intel hybrid CPUs (12th-14th gen), Setup.bat detects P-core count and writes a mask
:: covering only P-core threads. On AMD dual-CCD parts, it covers the first CCD.
:: 0xFF is a safe default on any CPU: it covers the first 4 hyperthreaded P-cores on hybrid
:: Intel, or the first 8 threads on non-hybrid / AMD, which is plenty for a single-threaded game.
set "_affinity=0xFF"
if exist "%METER_DIR%affinity.cfg" for /f "usebackq delims=" %%A in ("%METER_DIR%affinity.cfg") do set "_affinity=%%A"

cmd.exe /c start "EVERQUEST" /D "%EQ_DIR%" /affinity %_affinity% "%EQ_DIR%\eqgame.exe" patchme
